# Generated by Django 5.2.7 on 2025-10-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publicationyear',
            new_name='publication_year',
        ),
    ]
