# Generated by Django 5.2.6 on 2025-09-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_published_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_year',
            new_name='publication_year',
        ),
    ]
